/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.security;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.WindowManager;
import systems.tech247.securitypannels.GroupEditorTopComponent;
import systems.tech247.util.CapCreatable;


/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.security//Roles//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "RolesTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "systems.tech247.security.RolesTopComponent")
//@ActionReference(path = "Menu/System" , position = 250,separatorAfter=251)
//@TopComponent.OpenActionRegistration(
//        displayName = "#CTL_RolesAction",
//        preferredID = "RolesTopComponent"
//)
@Messages({
    "CTL_RolesAction=Roles (User Groups)",
    "CTL_RolesTopComponent=Roles (User Groups)",
    "HINT_RolesTopComponent="
})
public final class RolesTopComponent extends TopComponent
                                        implements ExplorerManager.Provider{
    ExplorerManager em= new ExplorerManager();
    QueryUserGroups query = new QueryUserGroups();
    InstanceContent content = new InstanceContent();
    Lookup lkp = new AbstractLookup(content);
    CapCreatable enableCreate;
    public RolesTopComponent() {
        initComponents();
        setName(Bundle.CTL_RolesTopComponent());
        setToolTipText(Bundle.HINT_RolesTopComponent());
        
        enableCreate = new CapCreatable() {
            @Override
            public void create() {
                TopComponent tc = new GroupEditorTopComponent();
                tc.open();
                tc.requestActive();
            }
        };
        
        content.add(enableCreate);
        
        setLayout(new BorderLayout());
        OutlineView btv = new OutlineView("Roles");
        
        String sqlString ="SELECT h FROM HrsGroups h";
        query.setSqlString(sqlString);
        
        add(btv,BorderLayout.CENTER);
        btv.getOutline().setRootVisible(false);
        em.setRootContext(new AbstractNode(Children.create(new ChildFactoryUserGroups(query,Boolean.FALSE), true)));
        associateLookup(new ProxyLookup(ExplorerUtils.createLookup(em, getActionMap()),lkp));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    @Override
    public ExplorerManager getExplorerManager(){
        return em;
    }
    
    
}
