/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.security;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.StatusDisplayer;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponentGroup;
import org.openide.windows.WindowManager;
import systems.tech247.util.CetusUTL;
import systems.tech247.util.NotifyUtil;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//systems.tech247.security//SecurityDashBoard//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SecurityDashBoardTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "systems.tech247.security.SecurityDashBoardTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
//@TopComponent.OpenActionRegistration(
//        displayName = "#CTL_SecurityDashBoardAction",
//        preferredID = "SecurityDashBoardTopComponent"
//)
@Messages({
    "CTL_SecurityDashBoardAction=SecurityDashBoard",
    "CTL_SecurityDashBoardTopComponent=Security DashBoard",
    "HINT_SecurityDashBoardTopComponent="
})
public final class SecurityDashBoardTopComponent extends TopComponent {
    TopComponentGroup group = WindowManager.getDefault().findTopComponentGroup("SCRGroup");
    public SecurityDashBoardTopComponent() {
        initComponents();
        setName(Bundle.CTL_SecurityDashBoardTopComponent());
        setToolTipText(Bundle.HINT_SecurityDashBoardTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
        showSCR();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }
    
    @Override
    protected void componentActivated() {
        super.componentActivated(); //To change body of generated methods, choose Tools | Templates.
        showSCR();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    void showSCR(){
        TopComponentGroup tcg = CetusUTL.currentTCG;
        if(tcg != null){
            
            tcg.close();
        }
//        //Close currently open TCs
//        for(TopComponent tc : WindowManager.getDefault().getRegistry().getOpened()){
//            tc.close();
//        }
        
        if(group != null){
            try{
                group.open();
                CetusUTL.currentTCG = group;
                //StatusDisplayer.getDefault().setStatusText("Group Opened");
            }catch(Exception ex){
                NotifyUtil.error("Error Opening Group", "There was an error opening this group", ex, false);
            }
        }
    }
}
