/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.editorpanels;

/**
 *
 * @author WKigenyi
 */
public class ModuleEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModuleEditorPanel
     */
    public ModuleEditorPanel() {
        initComponents();
    }
    
    public String getModuleCode(){
        return moduleCode.getText();
    }
    
    public String getModuleDescription(){
        return moduleDescription.getText();
    }
    
    public boolean getEnabled(){
        return moduleEnabled.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moduleCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        moduleDescription = new javax.swing.JTextField();
        moduleEnabled = new javax.swing.JCheckBox();

        moduleCode.setText(org.openide.util.NbBundle.getMessage(ModuleEditorPanel.class, "ModuleEditorPanel.moduleCode.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ModuleEditorPanel.class, "ModuleEditorPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ModuleEditorPanel.class, "ModuleEditorPanel.jLabel2.text")); // NOI18N

        moduleDescription.setText(org.openide.util.NbBundle.getMessage(ModuleEditorPanel.class, "ModuleEditorPanel.moduleDescription.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(moduleEnabled, org.openide.util.NbBundle.getMessage(ModuleEditorPanel.class, "ModuleEditorPanel.moduleEnabled.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moduleEnabled)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(moduleDescription)
                    .addComponent(moduleCode, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moduleEnabled)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField moduleCode;
    private javax.swing.JTextField moduleDescription;
    private javax.swing.JCheckBox moduleEnabled;
    // End of variables declaration//GEN-END:variables
}
